[package]
name = "dyn_array"
version = "0.1.6"
edition = "2021"
description = "A simple, easy to use N-dimensional dynamic array"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
